### PR TITLE
Typo in pre-commit example from README.md

### PR DESCRIPTION
**Pull request by syserr0r**
Hopefully self-explanatory

_\*Sending signal to you that this should get the magical label to silence the CHANGELOG entry check.\*_

### CODE REVIEW

**Comment by jsh9** [comment]
Thanks @syserr0r for correcting this typo!

**Comment by jsh9** [comment]
> *Sending signal to you that this should get the magical label to silence the CHANGELOG entry check.*

Hi @syserr0r , could you explain what this means?  I implemented the CHANGELOG entry check in Github workflow, but I think it's a bit buggy, so I'm actually thinking about disabling them.

**Comment by syserr0r** [comment]
> > _Sending signal to you that this should get the magical label to silence the CHANGELOG entry check._
> 
> Hi @syserr0r , could you explain what this means? I implemented the CHANGELOG entry check in Github workflow, but I think it's a bit buggy, so I'm actually thinking about disabling them.

It was in the placeholder text for the PR -- it said to send you the signal if it should get the magical label to silence the CHANGELOG entry check ¯\\\_(ツ)\_/¯

**Comment by jsh9** [comment]
Ah I see.  I inherited this template from Black when I forked it, so I didn't immediately realize where it came from.

**Pull request merged**
